-- Migration: Vytvorenie základnej štruktúry databázy pre EduPage klon. Vytváram tabuľky pre profily používateľov, rozvrh hodín, známky a správy. Nastavujem aj základné bezpečnostné pravidlá (RLS), aby boli dáta prístupné.
-- Executed at: 2025-12-03T02:02:13Z
-- Generated by AI Agent

-- Povolíme rozšírenie pre generovanie UUID
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Tabuľka profilov (prepojená s auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT NOT NULL,
    role TEXT CHECK (role IN ('student', 'teacher', 'parent')) DEFAULT 'student',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabuľka rozvrhu (Lessons)
CREATE TABLE IF NOT EXISTS public.lessons (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    subject TEXT NOT NULL,
    teacher TEXT NOT NULL,
    room TEXT,
    day_of_week INTEGER, -- 1 = Pondelok, 2 = Utorok...
    start_time TEXT, -- Uložíme ako string "08:00" pre jednoduchosť parsovania v UI
    end_time TEXT,
    color_hex TEXT, -- Hex kód farby, napr. "#FFCDD2"
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabuľka známok (Grades)
CREATE TABLE IF NOT EXISTS public.grades (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    student_id UUID REFERENCES public.profiles(id),
    subject TEXT NOT NULL,
    value TEXT NOT NULL,
    description TEXT,
    teacher_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabuľka správ (Messages)
CREATE TABLE IF NOT EXISTS public.messages (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    sender_id UUID REFERENCES public.profiles(id),
    recipient_id UUID REFERENCES public.profiles(id),
    sender_name TEXT, -- Meno odosielateľa pre jednoduchšie zobrazenie
    subject TEXT,
    content TEXT,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Zapnutie RLS (Row Level Security)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.grades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Vytvorenie politík pre prístup (zatiaľ otvorené pre vývoj)
DROP POLICY IF EXISTS "Enable read access for all users" ON public.profiles;
CREATE POLICY "Enable read access for all users" ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON public.profiles;
CREATE POLICY "Enable insert for authenticated users only" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Public read access" ON public.lessons;
CREATE POLICY "Public read access" ON public.lessons FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public access" ON public.grades;
CREATE POLICY "Public access" ON public.grades FOR ALL USING (true);

DROP POLICY IF EXISTS "Public access" ON public.messages;
CREATE POLICY "Public access" ON public.messages FOR ALL USING (true);

-- Vloženie ukážkových dát do rozvrhu (aby sme niečo videli hneď)
INSERT INTO public.lessons (subject, teacher, room, day_of_week, start_time, end_time, color_hex)
VALUES 
('Matematika', 'Mgr. Novák', 'Učebňa 101', 1, '08:00', '08:45', '#BBDEFB'), -- Modrá
('Slovenský jazyk', 'PaedDr. Kováčová', 'Učebňa 204', 1, '08:55', '09:40', '#FFCDD2'), -- Červená
('Anglický jazyk', 'Mgr. Smith', 'Jazyková učebňa', 1, '10:00', '10:45', '#FFE0B2'), -- Oranžová
('Fyzika', 'RNDr. Malý', 'Laboratórium', 1, '10:55', '11:40', '#E1BEE7'), -- Fialová
('Telesná výchova', 'Mgr. Rýchly', 'Telocvičňa', 1, '11:50', '12:35', '#C8E6C9'); -- Zelená

