// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: imjjqupjtejcpgthbyyl

class SupabaseConfig {
  static const String supabaseUrl = 'https://imjjqupjtejcpgthbyyl.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltampxdXBqdGVqY3BndGhieXlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2OTQ4MzYsImV4cCI6MjA4MDI3MDgzNn0.OuHyPpknaJeoHL-_hr4kfkKp0cPcTwBOrEphDJmmgUM';
}
